name: push and comment

on:
  push:
  workflow_run:
    workflows: ["build"]
    types: [completed]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to fetch the latest successful build artifacts from"
        required: true
        default: "main"
      pr_number:
        description: "PR number (only needed for manual runs)"
        required: true

jobs:
  push-and-comment:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.event == 'pull_request' &&
       github.event.workflow_run.conclusion == 'success' &&
       contains(github.event.workflow_run.head_commit.message, '[upload]')) ||
      (github.event_name == 'workflow_dispatch')
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CI_ARTIFACTS_GITLAB_DEPLOY_KEY }}

      - name: Checkout ci-artifacts
        run: |
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          git clone -b main git@gitlab.com:sunnypilot/public/ci-artifacts.git "${{ github.workspace }}/ci-artifacts"

      # Auto trigger: artifact by run_id
      - name: Download artifact (auto)
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v11
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: agnos-artifacts
          path: ${{ github.workspace }}/ci-artifacts

      # Manual trigger: latest successful artifacts from branch
      - name: Download artifact (manual)
        if: github.event_name == 'workflow_dispatch'
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: build
          branch: ${{ github.event.inputs.branch }}
          workflow_conclusion: success
          name: agnos-artifacts
          path: ${{ github.workspace }}/ci-artifacts

      - name: Read PR number and VERSION
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const prNumber = fs.readFileSync('${{ github.workspace }}/ci-artifacts/PR', 'utf8').trim();
            core.exportVariable('PR_NUMBER', prNumber);
            const version = fs.readFileSync('${{ github.workspace }}/ci-artifacts/VERSION', 'utf8').trim();
            core.exportVariable('VERSION', version);

      - name: Push boot, system and agnos.json
        working-directory: ${{ github.workspace }}/ci-artifacts
        run: |
          mv ota.json agnos.json && rm ota-staging.json
          git checkout -b agnos-builder/pr-${{ env.PR_NUMBER }}
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git lfs track "*.xz"
          git add .
          git commit -m "build artifacts for PR #${{ env.PR_NUMBER }}"
          git push origin agnos-builder/pr-${{ env.PR_NUMBER }} --force

      - name: List .xz files with links
        working-directory: ${{ github.workspace }}/ci-artifacts
        run: |
          {
            echo 'XZ_FILES<<EOF'
            for file in *.xz; do
              echo "* [$file](https://gitlab.com/sunnypilot/public/ci-artifacts/-/raw/agnos-builder/pr-${{ env.PR_NUMBER }}/$file)"
            done
            echo EOF
          } >> $GITHUB_ENV

      - name: Read agnos_stats.txt
        working-directory: ${{ github.workspace }}/ci-artifacts
        run: |
          {
            echo 'AGNOS_STATS<<EOF'
            cat agnos_stats.txt
            echo EOF
          } >> $GITHUB_ENV

      - name: Comment on PR
        if: github.event_name == 'workflow_run'
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6
        with:
          message: |
            <!-- _(run_id **${{ github.event.workflow_run.id }}**)_ -->
            ## :white_check_mark: AGNOS update ${{ env.VERSION }} ready
            In an openpilot branch, download <a href="https://gitlab.com/sunnypilot/public/ci-artifacts/-/raw/agnos-builder/pr-${{ env.PR_NUMBER }}/agnos.json">agnos.json</a> in `system/hardware/tici/` and update `AGNOS_VERSION` to "${{ env.VERSION }}" in `launch_env.sh`.

            For flashing locally, download and unarchive the images in `agnos-builder/output` and flash with `./flash_all.sh`.

            ### Images:
            ${{ env.XZ_FILES }}

            ### Stats:
            ```
            ${{ env.AGNOS_STATS }}
            ```
          pr_number: ${{ env.PR_NUMBER }}
          comment_tag: run_id
          mode: recreate
